name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install-libs1
      run: |
        sudo apt install -y libgmp-dev gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11  --slave /usr/bin/cpp cpp /usr/bin/cpp-11
    - name: cuda-toolkit
      # You may pin to the exact commit or the version.
      # uses: Jimver/cuda-toolkit@8022558310ea543e35132143092835585f60e628
      uses: Jimver/cuda-toolkit@v0.2.21
      with:
        cuda: '11.8.0'
    - name: make
      run: make gpu=1 CCAP=75 all
      working-directory: KeyHunt-Cuda
